### ISSUE TITLE
Add Code Coverage report & badge via Github Actions

### ISSUE THREAD

**Issue by RoussKS** [RoussKS/financial-year#13]
In TravisCI the automation was creating a clover file for code coverage and a badge as well.
`travis.yml` code below for reference

```yml
language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
