### ISSUE TITLE
Add composer cache for lock file (so no need to rebuild) in Github actions

### ISSUE THREAD

**Issue by RoussKS** [RoussKS/financial-year#14]
In Travis CI automation, the composer libraries & files were cached so there was no need to redownload.

Check options (via more github actions in the marketplace) to achieve this

```yml
language: php

sudo: false

cache:
  directories:
  - $HOME/.composer/cache/files

php:
  - '7.1'
  - '7.2'
  - '7.3'

before_install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
```
